---
blank_issues_enabled: false
contact_links:
- name: Feature requests
  url: https://github.com/hynek/svcs/discussions/categories/ideas
- name: Questions
  url: https://github.com/hynek/svcs/discussions/categories/q-a
